primary_key: []
columns:
  - name: subject
    type: text
    nullable: true

  - name: sender
    type: text
    nullable: true

  - name: receiver
    type: text
    nullable: true

  - name: timestamp
    type: timestamp
    nullable: true

  - name: message_body
    type: text
    nullable: true

  - name: thread_id
    type: text
    nullable: true

  - name: email_types
    type: text
    nullable: true

  - name: email_status
    type: text
    nullable: true

  - name: email_criticality
    type: text
    nullable: true

  - name: product_types
    type: text
    nullable: true

  - name: agent_effectivity
    type: text
    nullable: true

  - name: agent_efficiency
    type: text
    nullable: true

  - name: customer_satisfaction
    type: float
    nullable: true
